blog/urls.py
from django.conf.urls import url
# import blog.views
from . import views
urlpatterns = [
    url(r'^index/$', views.index,name='index'),
    url(r'^article/(?P<article_id>[0-9]+)$', views.article_page, name='article_page'),
    url(r'^edit/(?P<article_id>[0-9]+)$', views.edit_page, name='edit_page'),
    url(r'^edit/action/$', views.edit_action, name='edit_action'),
]

myblog/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls',namespace='blog')),
]

blog/models.py
from django.db import models

# Create your models here.


class Article(models.Model):
    title = models.CharField(max_length=200, default='Title')
    content = models.TextField(null=True)
    date = models.DateTimeField(auto_now_add=True)

blog/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.
from . import models


def index(request):
    articles = models.Article.objects.all()
    return render(request, 'blog/index.html', {'articles': articles})


def article_page(request, article_id):
    article = models.Article.objects.get(pk=article_id)
    return render(request, "blog/article_page.html", {'article': article})


def edit_page(request, article_id):
    if str(article_id) == '0':
        return render(request, 'blog/edit_page.html')
    else:
        article = models.Article.objects.get(pk=article_id)
        return render(request, 'blog/edit_page.html', {'article': article})


def edit_action(request):
    article_id = request.POST.get('article_id', '0')
    title = request.POST.get('title', 'TITLE')
    content = request.POST.get('content', 'CONTENT')
    if article_id == '0':
        models.Article.objects.create(title=title, content=content)
        articles = models.Article.objects.all()
        return render(request, 'blog/index.html', {'articles': articles})
    else:
        article = models.Article.objects.get(pk=article_id)
        article.title = title
        article.content = content
        article.save()
        return render(request, 'blog/article_page.html', {'article': article})

blog/templates/blog/article_page.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <title>Article Page</title>
</head>

<body>
  <h1>{{article.title}}</h1>
  <br/>
  <h3>{{article.content}}</h3>
  <br/><br/>
  <a href="{% url 'blog:edit_page' article.id %}">修改文章</a>
</body>

</html>

blog/templates/blog/edit_page.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <title>Edit Page</title>
</head>

<body >
  <form action = "{% url 'blog:edit_action' %}" method = "post" >
    {% csrf_token %}
        <input type="hidden" name="article_id" value="{{article.id|default:'0'}}" />
        <label>
              文章标题 <input type = "text" name = "title" value = "{{article.title}}" />
        </label>
        <br/>
        <label>
              文章内容<input type="text" name="content" value="{{article.content}}"/>
        </label>
        <br/>
      <input type="submit">
  </form>
</body>


</html>

blog/templates/blog/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Title</title>
</head>
<body>
<h1>
    <a href="{% url 'blog:edit_page' 0 %}">新文章</a>
</h1>
{% for article in articles %}
<a href="{% url 'blog:article_page' article.id %}">{{article.title}}</a>
<br/>
{% endfor %}
</body>
</html>